# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "evraz_api"

development:
  <<: *common
  brokers:
    - rc1a-b5e65f36lm3an1d5.mdb.yandexcloud.net:9091

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - rc1a-b5e65f36lm3an1d5.mdb.yandexcloud.net:9091
